Repository TEXT-ARENA/TEXT-ARENA_BE, pull requests merged in 2025-06, with the labels that each got.

#10 [SETTING] 스웨거 세팅
  build.gradle
  src/main/java/cc/team3/global/config/SwaggerConfig.java
Labels: ⚙ Setting

#8 [FEATURE] 캐릭터 엔티티 생성
  src/main/java/cc/team3/character/domain/Character.java
Labels: ✨ Feature

#14 [REFACTOR] #1: 유저 엔티티 속성 변경
  src/main/java/cc/team3/user/domain/User.java
Labels: 🔨 Refactor

#22 [FEATURE] 캐릭터 생성 API 구현
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/converter/EquipmentConverter.java
  src/main/java/cc/team3/character/domain/Effect.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
  src/main/java/cc/team3/character/service/CharacterService.java
  src/main/java/cc/team3/global/feignclient/AiServerClient.java
Labels: 📬 API, ✨ Feature

#27 [FEATURE] 유저별 캐릭터 목록 조회 API 구현
  src/main/java/cc/team3/character/controller/CharacterController.java
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
  src/main/java/cc/team3/character/repository/CharacterRepository.java
  src/main/java/cc/team3/character/service/CharacterService.java
Labels: 📬 API, ✨ Feature

#29 [FEATURE] 내 캐릭터 & 전투 상대 캐릭터 상세 조회 API 구현
  src/main/java/cc/team3/character/controller/CharacterController.java
  src/main/java/cc/team3/character/repository/CharacterRepository.java
  src/main/java/cc/team3/character/service/CharacterService.java
  src/main/java/cc/team3/global/apiPayload/status/ErrorStatus.java
Labels: 📬 API, ✨ Feature

#31 [FEATURE] 캐릭터 삭제 API 구현
  src/main/java/cc/team3/character/controller/CharacterController.java
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
  src/main/java/cc/team3/character/service/CharacterService.java
Labels: 📬 API, ✨ Feature

#34 [FEATURE] 캐릭터 목록 조회 시 승패 기록, 경험치 정보 추가
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
Labels: 📬 API, ✨ Feature

#40 [REFACTOR] 장비 생성 응답 값 수정
  src/main/java/cc/team3/character/converter/EquipmentConverter.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
  src/main/java/cc/team3/character/service/CharacterService.java
  src/main/java/cc/team3/character/service/EquipmentService.java
Labels: 📬 API, 🔨 Refactor

#42 [FIX] CharacterResponse의 ReadCharacterListDTO 내 loses를 losses로 변경
  src/main/java/cc/team3/character/dto/CharacterResponse.java
Labels: 🔨 Refactor

#44 [FEATURE] 캐릭터 장비 조회 API 구현
  src/main/java/cc/team3/character/controller/CharacterController.java
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/domain/enums/EquipmentType.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
  src/main/java/cc/team3/character/repository/CharacterRepository.java
  src/main/java/cc/team3/character/service/CharacterService.java
Labels: 📬 API, ✨ Feature

#48 [REFACTOR] 캐릭터 삭제 시 속한 장비도 모두 삭제되도록 로직 추가
  src/main/java/cc/team3/character/repository/EquipmentRepository.java
  src/main/java/cc/team3/character/service/CharacterService.java
  src/main/java/cc/team3/character/service/EquipmentService.java
Labels: 🔨 Refactor

#50 Feat/#49
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
Labels: 📬 API, ✨ Feature

#56 [REFACTOR] 장비 컬렉션 속성 수정.
  src/main/java/cc/team3/character/controller/CharacterController.java
  src/main/java/cc/team3/character/converter/CharacterConverter.java
  src/main/java/cc/team3/character/converter/EquipmentConverter.java
  src/main/java/cc/team3/character/domain/Equipment.java
  src/main/java/cc/team3/character/dto/CharacterResponse.java
Labels: 🔨 Refactor
